kind: Deployment
apiVersion: apps/v1
metadata:
  name: swisnap-agent-k8s-event-collector
  namespace: kube-system
  labels:
    app: swisnap-agent-k8s-event-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swisnap-agent-k8s-event-collector
  template:
    metadata:
      labels:
        app: swisnap-agent-k8s-event-collector
    spec:
      serviceAccountName: swisnap-agent-serviceaccount
      containers:
        - name: swisnap-agent-k8s-event-collector
          image: 'solarwinds/solarwinds-snap-agent-docker:latest'
          imagePullPolicy: Always
          volumeMounts:
            - name: plugins-vol
              mountPath: /opt/SolarWinds/Snap/etc/plugins.d
            - name: tasks-vol
              mountPath: /opt/SolarWinds/Snap/etc/tasks.d
          env:
            - name: APPOPTICS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: appoptics-token
                  key: APPOPTICS_TOKEN
            - name: SWISNAP_ENABLE_KUBERNETES # turn off default plugin configuration
              value: 'false'
          envFrom:
            - configMapRef:
                name: swisnap-agent-k8s-configmap
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /v1/plugins
              port: 21413
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/plugins
              port: 21413
            initialDelaySeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: plugins-vol
          configMap:
            name: plugin-configs
            items:
              - key: kubernetes.yaml
                path: kubernetes.yaml
              - key: logs.yaml
                path: logs.yaml
        - name: tasks-vol
          configMap:
            name: task-manifests
            items:
              - key: task-aokubernetes.yaml
                path: task-aokubernetes.yaml
              - key: task-logs.yaml
                path: task-logs.yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
